# Learning Numpy
## 1)Create an array of zeros, ones, and a range

In [2]:
import numpy as np

a = np.zeros((3, 4))           # 3x4 array of zeros
b = np.ones((2, 2))            # 2x2 array of ones
c = np.arange(10)              # Array from 0 to 9
d = np.linspace(0, 1, 5)       # 5 numbers between 0 and 1
print(a)
print(b)
print(c)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


## 2)Basic indexing and slicing

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])       # Slice from index 1 to 3
print(arr[::-1])      # Reverse array


[20 30 40]
[50 40 30 20 10]


#3)Reshape and flatten arrays

arr = np.arange(12)
print(arr)
reshaped = arr.reshape((3, 4))
print(reshaped)
flat = reshaped.flatten()
print(flat)


## 3)Matrix Operation

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
print(A + B)          # Element-wise addition
print(A @ B)          # Matrix multiplication
print(A.T)            # Transpose


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## 4)Boolean indexing and filtering

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[arr % 2 == 0])   # Even numbers


[2 4 6]


## 5)Random Number Generator

In [6]:
np.random.seed(0)
rand_arr = np.random.rand(3, 3)    # Uniform random numbers
norm_arr = np.random.randn(3, 3)   # Normal distribution
print("Rand_arr",rand_arr,"\n")
print("Norm_arr",norm_arr)


Rand_arr [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]] 

Norm_arr [[ 1.26611853 -0.50587654  2.54520078]
 [ 1.08081191  0.48431215  0.57914048]
 [-0.18158257  1.41020463 -0.37447169]]


## 6)Broadcasting

In [13]:
A = np.array([[1], [2], [3]])
B = np.array([4, 5, 6])
print(A + B)  # Broadcasting will expand A to match B


[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 7)Fancy indexing

In [7]:
arr = np.array([10, 20, 30, 40, 50])
idx = [1, 3, 4]
print(arr[idx])


[20 40 50]


## 8)Apply a custom function to an array

In [8]:
def custom_fn(x):
    return x**2 + 3*x + 5

arr = np.array([0, 1, 2, 3])
result = custom_fn(arr)
print(result)


[ 5  9 15 23]


## 9)Statistics and aggregation

In [9]:
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print(np.mean(arr, axis=0))    # Mean of each column
print(np.std(arr))             # Standard deviation
print(np.sum(arr, axis=1))     # Sum of each row

[[32 65  9 57 32]
 [31 74 23 35 75]
 [55 28 34  0  0]
 [36 53  5 38 17]
 [79  4 42 58 31]]
[46.6 44.8 22.6 37.6 31. ]
23.021937364175066
[195 238 117 149 214]
